src/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :birthplaces
  resources :prefectures
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/birthplace.rb
class Birthplace < ApplicationRecord
  belongs_to :prefecture
  belongs_to :user
end

src/app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :birthplaces
  has_many :users, through: :birthplaces

  validates :name, presence: true, uniqueness: true
end

src/app/models/user.rb
class User < ApplicationRecord
  has_one :birthplace, dependent: :destroy
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

src/app/controllers/birthplaces_controller.rb
class BirthplacesController < ApplicationController
  before_action :set_birthplace, only: %i[ show edit update destroy ]

  # GET /birthplaces or /birthplaces.json
  def index
    @birthplaces = Birthplace.all
  end

  # GET /birthplaces/1 or /birthplaces/1.json
  def show
  end

  # GET /birthplaces/new
  def new
    @birthplace = Birthplace.new
  end

  # GET /birthplaces/1/edit
  def edit
  end

  # POST /birthplaces or /birthplaces.json
  def create
    @birthplace = Birthplace.new(birthplace_params)

    respond_to do |format|
      if @birthplace.save
        format.html { redirect_to birthplace_url(@birthplace), notice: "Birthplace was successfully created." }
        format.json { render :show, status: :created, location: @birthplace }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @birthplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /birthplaces/1 or /birthplaces/1.json
  def update
    respond_to do |format|
      if @birthplace.update(birthplace_params)
        format.html { redirect_to birthplace_url(@birthplace), notice: "Birthplace was successfully updated." }
        format.json { render :show, status: :ok, location: @birthplace }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @birthplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birthplaces/1 or /birthplaces/1.json
  def destroy
    @birthplace.destroy

    respond_to do |format|
      format.html { redirect_to birthplaces_url, notice: "Birthplace was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_birthplace
      @birthplace = Birthplace.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def birthplace_params
      params.require(:birthplace).permit(:prefecture_id, :detail, :user_id)
    end
end

src/app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  before_action :set_prefecture, only: %i[ edit update destroy ]

  # GET /prefectures or /prefectures.json
  def index
    @prefectures = Prefecture.preload(:users)
  end

  # GET /prefectures/1 or /prefectures/1.json
  def show
    @prefecture = Prefecture.preload(:users).find(params[:id])
  end

  # GET /prefectures/new
  def new
    @prefecture = Prefecture.new
  end

  # GET /prefectures/1/edit
  def edit
  end

  # POST /prefectures or /prefectures.json
  def create
    @prefecture = Prefecture.new(prefecture_params)

    respond_to do |format|
      if @prefecture.save
        format.html { redirect_to prefecture_url(@prefecture), notice: "Prefecture was successfully created." }
        format.json { render :show, status: :created, location: @prefecture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prefectures/1 or /prefectures/1.json
  def update
    respond_to do |format|
      if @prefecture.update(prefecture_params)
        format.html { redirect_to prefecture_url(@prefecture), notice: "Prefecture was successfully updated." }
        format.json { render :show, status: :ok, location: @prefecture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prefectures/1 or /prefectures/1.json
  def destroy
    @prefecture.destroy

    respond_to do |format|
      format.html { redirect_to prefectures_url, notice: "Prefecture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prefecture
      @prefecture = Prefecture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prefecture_params
      params.require(:prefecture).permit(:name)
    end
end

src/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @form = UsersSearchForm.new(users_search_form_params)
    @users = @form.search
  end

  def show
  end

  def new
    @form = UserForm.new
  end

  def create
    @form = UserForm.new(user_form_params)

    respond_to do |format|
      if @form.save
        @user = User.last
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @form = UserForm.new(user: @user)
  end

  def update
    @form = UserForm.new(user_form_params, user: @user)

    respond_to do |format|
      if @form.save
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_form_params
      params.require(:user).permit(UserForm::ATTRIBUTES)
    end

    def users_search_form_params
      return {} if params[:users_search_form].blank?

      params.require(:users_search_form).permit(UsersSearchForm::ATTRIBUTES)
    end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/birthplaces_helper.rb
module BirthplacesHelper
end

src/app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

src/app/helpers/users_helper.rb
module UsersHelper
end

src/app/views/birthplaces/_form.html.erb
<%= form_with(model: birthplace) do |form| %>
  <% if birthplace.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(birthplace.errors.count, "error") %> prohibited this birthplace from being saved:</h2>

      <ul>
        <% birthplace.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prefecture_id %>
    <%= form.text_field :prefecture_id %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_field :detail %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/birthplaces/edit.html.erb
<h1>Editing Birthplace</h1>

<%= render 'form', birthplace: @birthplace %>

<%= link_to 'Show', @birthplace %> |
<%= link_to 'Back', birthplaces_path %>

src/app/views/birthplaces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Birthplaces</h1>

<table>
  <thead>
    <tr>
      <th>Prefecture</th>
      <th>Detail</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @birthplaces.each do |birthplace| %>
      <tr>
        <td><%= birthplace.prefecture_id %></td>
        <td><%= birthplace.detail %></td>
        <td><%= birthplace.user_id %></td>
        <td><%= link_to 'Show', birthplace %></td>
        <td><%= link_to 'Edit', edit_birthplace_path(birthplace) %></td>
        <td><%= link_to 'Destroy', birthplace, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Birthplace', new_birthplace_path %>

src/app/views/birthplaces/new.html.erb
<h1>New Birthplace</h1>

<%= render 'form', birthplace: @birthplace %>

<%= link_to 'Back', birthplaces_path %>

src/app/views/birthplaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prefecture:</strong>
  <%= @birthplace.prefecture_id %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @birthplace.detail %>
</p>

<p>
  <strong>User:</strong>
  <%= @birthplace.user_id %>
</p>

<%= link_to 'Edit', edit_birthplace_path(@birthplace) %> |
<%= link_to 'Back', birthplaces_path %>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'User Index', users_path %>
    <%= link_to 'New User', new_user_path %>
    <%= link_to 'Prefecture Index', prefectures_path %>

    <%= yield %>
  </body>
</html>

src/app/views/prefectures/_form.html.erb
<%= form_with(model: prefecture) do |form| %>
  <% if prefecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prefecture.errors.count, "error") %> prohibited this prefecture from being saved:</h2>

      <ul>
        <% prefecture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/prefectures/edit.html.erb
<h1>Editing Prefecture</h1>

<%= render 'form', prefecture: @prefecture %>

<%= link_to 'Show', @prefecture %> |
<%= link_to 'Back', prefectures_path %>

src/app/views/prefectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prefectures Index</h1>
<h2><%= @prefectures.size %> Prefectures</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prefectures.each do |prefecture| %>
      <tr>
        <td><%= prefecture.name %></td>
        <td><%= prefecture.users.size %></td>
        <td><%= link_to 'Show', prefecture %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

src/app/views/prefectures/new.html.erb
<h1>New Prefecture</h1>

<%= render 'form', prefecture: @prefecture %>

<%= link_to 'Back', prefectures_path %>

src/app/views/prefectures/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Name: <%= @prefecture.name %>
</h1>
<h2>
  User: <%= @prefecture.users.size %>

  <% case @prefecture.users.size %>
  <% when 0 %>
  <% when 1 %>
    Person
  <% else %>
    People
  <% end %>
</h2>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Born on</th>
      <th>Birthplace</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prefecture.users.each do |user| %>
      <tr>
        <td><%= user.last_name %></td>
        <td><%= user.first_name %></td>
        <td><%= user.born_on %></td>
        <td><%= user.birthplace&.prefecture&.name %></td>
        <td><%= user.birthplace&.detail %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_prefecture_path(@prefecture) %> |
<%= link_to 'Back', prefectures_path %>

src/app/views/users/_form.html.erb
<%= form_with(model: form, url: url) do |form| %>
  <%# if @form.errors.any? %>
    <%# <div id="error_explanation"> %>
      <%# <h2>= pluralize(form.errors.count, "error") prohibited this user from being saved:</h2> %>

      <%# <ul> %>
        <%# <% form.errors.each do |error| %>
          <%# <li>= error.full_message</li> %>
        <%# end %>
      <%# </ul> %>
    <%# </div> %>
  <%# <% end %>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :born_on %>
    <%= form.date_select :born_on, { start_year: (Time.now.year), end_year: (Time.now.year - 70), prompt: "--", use_month_numbers: true } %>
  </div>

  <div class="field">
    <%= form.label :prefecture_id %>
    <%= form.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: '選択してください' %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_field :detail %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', form: @form, url: user_path %>

<%= link_to 'Show', user_path(@user) %> |
<%= link_to 'Back', users_path %>

src/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<h2><%= @users.size %>/<%= User.all.size %></h2>


<%= form_with(model: @form , url: users_path ,method: :get) do |form| %>
  <%= form.label :last_name %>
  <%= form.search_field :last_name %>
  <%= form.label :first_name %>
  <%= form.search_field :first_name %>
  <%= form.label :born_on_year %>
  <%= form.select :born_on_year, 1960..2000, include_blank: '年' %>
  <%= form.label :born_on_month %>
  <%= form.select :born_on_month, 1..12, include_blank: '月' %>
  <%= form.label :prefecture_id %>
  <%= form.collection_select :prefecture_id, Prefecture.all, :id, :name, include_blank: '出身地' %>
  <%= form.submit '検索' %>
<% end %>


<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Born on</th>
      <th>Birthplace</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.last_name %></td>
        <td><%= user.first_name %></td>
        <td><%= user.born_on %></td>
        <td><%= user.birthplace&.prefecture&.name %></td>
        <td><%= user.birthplace&.detail %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

src/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', form: @form, url: users_path %>

<%= link_to 'Back', users_path %>

src/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Born on:</strong>
  <%= @user.born_on %>
</p>

<p>
  <strong>Birthplace:</strong>
  <%= @user.birthplace.prefecture.name %>
  <%= @user.birthplace.detail %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>